# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import buffer_pb2 as buffer__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in buffer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BufferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddExperience = channel.unary_unary(
                '/buffer.BufferService/AddExperience',
                request_serializer=buffer__pb2.AddRequest.SerializeToString,
                response_deserializer=buffer__pb2.AddResponse.FromString,
                _registered_method=True)
        self.SampleBatch = channel.unary_unary(
                '/buffer.BufferService/SampleBatch',
                request_serializer=buffer__pb2.SampleRequest.SerializeToString,
                response_deserializer=buffer__pb2.SampleResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/buffer.BufferService/GetStatus',
                request_serializer=buffer__pb2.StatusRequest.SerializeToString,
                response_deserializer=buffer__pb2.StatusResponse.FromString,
                _registered_method=True)


class BufferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddExperience(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SampleBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BufferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddExperience': grpc.unary_unary_rpc_method_handler(
                    servicer.AddExperience,
                    request_deserializer=buffer__pb2.AddRequest.FromString,
                    response_serializer=buffer__pb2.AddResponse.SerializeToString,
            ),
            'SampleBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleBatch,
                    request_deserializer=buffer__pb2.SampleRequest.FromString,
                    response_serializer=buffer__pb2.SampleResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=buffer__pb2.StatusRequest.FromString,
                    response_serializer=buffer__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'buffer.BufferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('buffer.BufferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BufferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddExperience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/AddExperience',
            buffer__pb2.AddRequest.SerializeToString,
            buffer__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SampleBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/SampleBatch',
            buffer__pb2.SampleRequest.SerializeToString,
            buffer__pb2.SampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/buffer.BufferService/GetStatus',
            buffer__pb2.StatusRequest.SerializeToString,
            buffer__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
