# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: buffer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'buffer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62uffer.proto\x12\x06\x62uffer\"4\n\nAddRequest\x12\x13\n\x0b\x65xperiences\x18\x01 \x01(\x0c\x12\x11\n\tsource_id\x18\x02 \x01(\t\"/\n\x0b\x41\x64\x64Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\rSampleRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\"$\n\x0eSampleResponse\x12\x12\n\nbatch_data\x18\x01 \x01(\x0c\"\x0f\n\rStatusRequest\"H\n\x0eStatusResponse\x12\x14\n\x0c\x63urrent_size\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61pacity\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t2\xc9\x01\n\rBufferService\x12:\n\rAddExperience\x12\x12.buffer.AddRequest\x1a\x13.buffer.AddResponse\"\x00\x12>\n\x0bSampleBatch\x12\x15.buffer.SampleRequest\x1a\x16.buffer.SampleResponse\"\x00\x12<\n\tGetStatus\x12\x15.buffer.StatusRequest\x1a\x16.buffer.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buffer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=24
  _globals['_ADDREQUEST']._serialized_end=76
  _globals['_ADDRESPONSE']._serialized_start=78
  _globals['_ADDRESPONSE']._serialized_end=125
  _globals['_SAMPLEREQUEST']._serialized_start=127
  _globals['_SAMPLEREQUEST']._serialized_end=162
  _globals['_SAMPLERESPONSE']._serialized_start=164
  _globals['_SAMPLERESPONSE']._serialized_end=200
  _globals['_STATUSREQUEST']._serialized_start=202
  _globals['_STATUSREQUEST']._serialized_end=217
  _globals['_STATUSRESPONSE']._serialized_start=219
  _globals['_STATUSRESPONSE']._serialized_end=291
  _globals['_BUFFERSERVICE']._serialized_start=294
  _globals['_BUFFERSERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
