# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.rollout_pb2 as rollout__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rollout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RolloutServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CollectExperience = channel.unary_unary(
                '/rollout.RolloutService/CollectExperience',
                request_serializer=rollout__pb2.CollectRequest.SerializeToString,
                response_deserializer=rollout__pb2.CollectResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/rollout.RolloutService/GetStatus',
                request_serializer=rollout__pb2.StatusRequest.SerializeToString,
                response_deserializer=rollout__pb2.StatusResponse.FromString,
                _registered_method=True)


class RolloutServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CollectExperience(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RolloutServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CollectExperience': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectExperience,
                    request_deserializer=rollout__pb2.CollectRequest.FromString,
                    response_serializer=rollout__pb2.CollectResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=rollout__pb2.StatusRequest.FromString,
                    response_serializer=rollout__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rollout.RolloutService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rollout.RolloutService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RolloutService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CollectExperience(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollout.RolloutService/CollectExperience',
            rollout__pb2.CollectRequest.SerializeToString,
            rollout__pb2.CollectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollout.RolloutService/GetStatus',
            rollout__pb2.StatusRequest.SerializeToString,
            rollout__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
