# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rollout.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rollout.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrollout.proto\x12\x07rollout\"R\n\x0e\x43ollectRequest\x12\x16\n\x0epolicy_weights\x18\x01 \x01(\x0c\x12\x11\n\tnum_steps\x18\x02 \x01(\x05\x12\x15\n\rcollection_id\x18\x03 \x01(\t\"\xa5\x01\n\x0f\x43ollectResponse\x12\x13\n\x0b\x65xperiences\x18\x01 \x01(\x0c\x12\x15\n\rcollection_id\x18\x02 \x01(\t\x12\x36\n\x07metrics\x18\x03 \x03(\x0b\x32%.rollout.CollectResponse.MetricsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x0f\n\rStatusRequest\"J\n\x0eStatusResponse\x12\x13\n\x0bnum_workers\x18\x01 \x01(\x05\x12\x13\n\x0btotal_steps\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t2\x9a\x01\n\x0eRolloutService\x12H\n\x11\x43ollectExperience\x12\x17.rollout.CollectRequest\x1a\x18.rollout.CollectResponse\"\x00\x12>\n\tGetStatus\x12\x16.rollout.StatusRequest\x1a\x17.rollout.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rollout_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLECTRESPONSE_METRICSENTRY']._loaded_options = None
  _globals['_COLLECTRESPONSE_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_COLLECTREQUEST']._serialized_start=26
  _globals['_COLLECTREQUEST']._serialized_end=108
  _globals['_COLLECTRESPONSE']._serialized_start=111
  _globals['_COLLECTRESPONSE']._serialized_end=276
  _globals['_COLLECTRESPONSE_METRICSENTRY']._serialized_start=230
  _globals['_COLLECTRESPONSE_METRICSENTRY']._serialized_end=276
  _globals['_STATUSREQUEST']._serialized_start=278
  _globals['_STATUSREQUEST']._serialized_end=293
  _globals['_STATUSRESPONSE']._serialized_start=295
  _globals['_STATUSRESPONSE']._serialized_end=369
  _globals['_ROLLOUTSERVICE']._serialized_start=372
  _globals['_ROLLOUTSERVICE']._serialized_end=526
# @@protoc_insertion_point(module_scope)
